version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Tu05102000@
      - DATABASE_NAME=websiteblog
      - REDIS_HOST=redis
      - REDIS_PORT=6380
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Tu05102000@
      MYSQL_DATABASE: websiteblog
      MYSQL_USER: mysql
      MYSQL_PASSWORD: Tu05102000@
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
  cron:
    build:
      context: .
      dockerfile: DockerFile.cron
    container_name: cron
    volumes:
      - ./backup:/backup
    depends_on:
      - mysql

volumes:
  mysql_data:
  redis_data:
  backup: